language: node_js

# Node versions: https://node.green/

os:
  - "osx"
  - "linux"
  - "windows"

node_js:
  - "11.5.0"
  - "8.6.0"

sudo: false
cache: npm

before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  - "npm install coveralls"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

script:
  - npm run ci
